// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BooleanDisplay: typeof import('./theme/components/BooleanDisplay.vue')['default']
    'Carbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    CarbonCheckmark: typeof import('~icons/carbon/checkmark')['default']
    CarbonError: typeof import('~icons/carbon/error')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Changelog: typeof import('./theme/components/Changelog.vue')['default']
    ChangeLog: typeof import('./theme/components/ChangeLog.vue')['default']
    Components: typeof import('./theme/components/Components.vue')['default']
    ComponentsGuide: typeof import('./theme/components/ComponentsGuide.vue')['default']
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    FunctionBadge: typeof import('./theme/components/FunctionBadge.vue')['default']
    FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeFeatures: typeof import('./theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./theme/components/HomeHero.vue')['default']
    LearnMoreComponents: typeof import('./theme/components/LearnMoreComponents.vue')['default']
    Note: typeof import('./theme/components/Note.vue')['default']
    OcticonGitCommit16: typeof import('~icons/octicon/git-commit16')['default']
    OcticonGitCommit24: typeof import('~icons/octicon/git-commit24')['default']
    OcticonGitPullRequestDraft16: typeof import('~icons/octicon/git-pull-request-draft16')['default']
    OcticonRocket16: typeof import('~icons/octicon/rocket16')['default']
    ReloadPrompt: typeof import('./theme/components/ReloadPrompt.vue')['default']
  }
}

export { }
